name: flutter_gen_ai_chat_ui
description: "Modern Flutter chat UI with streaming text, markdown support, file attachments, and customizable themes. Perfect for AI assistants, customer support, and messaging apps."
version: 2.3.6
homepage: https://github.com/hooshyar/flutter_gen_ai_chat_ui
repository: https://github.com/hooshyar/flutter_gen_ai_chat_ui
issue_tracker: https://github.com/hooshyar/flutter_gen_ai_chat_ui/issues
documentation: https://github.com/hooshyar/flutter_gen_ai_chat_ui/blob/main/README.md
funding:
  - https://github.com/sponsors/hooshyar
topics: [flutter, chat, ui, messaging, ai, chatbot, streaming, markdown, attachments, customizable, cross-platform, sdk]

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown_plus: ^1.0.3
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  flutter_streaming_text_markdown: ^1.2.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  speech_to_text: ^7.2.0
  network_image_mock: ^2.1.1
  golden_toolkit: ^0.15.0
  integration_test:
    sdk: flutter
  provider: ^6.1.2

flutter:
  uses-material-design: true
